### PR TITLE
Webpack 2

### PR DESCRIPTION
**Pull request by skovhus**
💣 do not merge, this is an experiment with webpack 2 💣 

I've made our webpack 1 setup fairly compatible with webpack 2. This branch demonstrate what needs to be done in order to upgrade. 

My measurements show that we suffer a slowdown, specially in consecutive development builds... But production build is faster.

I think we should wait until webpack is out of beta before trying this again.

### Development build

`./node_modules/.bin/webpack --config webpack/config.dev.js `

*Cold cache*
Webpack 1.13.3: 15-16 seconds 
Webpack 2.1.0-beta.26: 28 seconds
Webpack 2.1.0-beta.27: 27 seconds
Webpack 2.2.0-rc.0: 22 seconds

*Warm cache*
Webpack 1.13.3: 9 seconds
Webpack 2.1.0-beta.26: 19 seconds
Webpack 2.1.0-beta.27: 18 seconds
Webpack 2.2.0-rc.0: 16 seconds

*Watch mode rebuilds*

Webpack .13.3: 1.2-1.5 s
Webpack 2.2.0-rc.0: 1.2-1.3 s

### Production build

`./node_modules/.bin/webpack -p --config webpack/config.prod.js `
Webpack 1.13.3: 90 seconds
Webpack 2.1.0-beta.27: 48 seconds
Webpack 2.2.0-rc.0: 49 seconds

### CODE REVIEW

**Comment by skovhus** [comment]
I'll open an issue for the webpack 2 maintainers.

**Comment by kkateq** [comment]
@skovhus webpack 2.2.0-rc came out yesterday and maintainers asked for an upgrade to the latest RC for bugs reporting, so make sense to check it out

**Comment by skovhus** [comment]
Yes. Came out after I reported the issue to them. So I'm going to test this again. 😊

**Comment by skovhus** [comment]
@kkateq I think we can live with this slowdown for dev builds as watch mode is still as fast.

**Comment by kkateq** [comment]
@skovhus if it's `dev` then for sure we can 👍

**Comment by skovhus** [comment]
Blocked on https://github.com/benmosher/eslint-plugin-import/issues/688

**Comment by skovhus** [comment]
@kkateq Now it works : )

**Comment by skovhus** [comment]
Nah... watch mode is now a bit broken... Will try to investigate that a bit.

**Comment by skovhus** [comment]
https://github.com/skovhus/webpack-2-slowness/tree/watch-mode

**Comment by skovhus** [comment]
They fixed the watch bug in 2.2.0-rc.1...

**Comment by skovhus** [comment]
Works now but blocked on flow errors on master.

**Pull request merged**
